/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckableTag: typeof import('ant-design-vue/es')['CheckableTag']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddTagModal: typeof import('./src/components/AddTagModal/index.vue')['default']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    BaseModal: typeof import('./src/components/BaseModal/index.vue')['default']
    BaseTag: typeof import('./src/components/BaseTag/index.vue')['default']
    CommonTagArea: typeof import('./src/components/AddTagModal/components/CommonTagArea.vue')['default']
    CommonTagItem: typeof import('./src/components/AddTagModal/components/CommonTagItem.vue')['default']
    InputSearch: typeof import('./src/components/AddTagModal/components/InputSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/Scroll/index.vue')['default']
    SearchAddTag: typeof import('./src/components/AddTagModal/components/SearchAddTag.vue')['default']
    SearchBar: typeof import('./src/components/FullSearch/SearchBar.vue')['default']
    SearchTagArea: typeof import('./src/components/AddTagModal/components/SearchTagArea.vue')['default']
    SelectedTagArea: typeof import('./src/components/AddTagModal/components/SelectedTagArea.vue')['default']
    TagListArea: typeof import('./src/components/AddTagModal/components/TagListArea.vue')['default']
    TagTypeModal: typeof import('./src/components/AddTagModal/components/TagTypeModal.vue')['default']
  }
}
